# Generated by Django 6.0.1 on 2026-02-03 04:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='5MB 이하, 1000x1000 픽셀', upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='사진')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '사진 업로드',
                'verbose_name_plural': '사진 업로드',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to='receipts/%Y/%m/%d/', verbose_name='영수증 이미지')),
                ('ocr_text', models.TextField(blank=True, verbose_name='OCR 추출 텍스트')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='처리일시')),
                ('is_processed', models.BooleanField(default=False, verbose_name='처리완료')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '영수증 OCR',
                'verbose_name_plural': '영수증 OCR',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(max_length=200, verbose_name='내용')),
                ('visibility', models.CharField(choices=[('public', '공개'), ('private', '비공개')], default='public', max_length=10, verbose_name='공개여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='homecook_po_created_c4706e_idx'), models.Index(fields=['visibility', '-created_at'], name='homecook_po_visibil_818b92_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='레시피 제목')),
                ('content', models.TextField(max_length=300, verbose_name='레시피 내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/%Y/%m/%d/', verbose_name='레시피 사진')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '레시피',
                'verbose_name_plural': '레시피',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='homecook_re_created_a43436_idx'), models.Index(fields=['user', '-created_at'], name='homecook_re_user_id_f52e27_idx')],
            },
        ),
    ]
